name: Import Photos from Google Drive

# trigger manually or on a schedule
on:
  workflow_dispatch:
  # uncomment the next lines if you want it to run daily at midnight UTC
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      # 1. check out your repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. install gdown (a tiny Python utility)
      - name: Install gdown
        run: pip install gdown

      # 3. pull your Drive folder into `photos/`
      - name: Download photos folder
        run: |
          # replace FOLDER_ID below with the ID from your Drive URL:
          # e.g. if your link is
          #   https://drive.google.com/drive/folders/1aBcD_efGHIjKlmn2OP3qr
          # then FOLDER_ID is 1aBcD_efGHIjKlmn2OP3qr
          gdown "https://drive.google.com/drive/folders/1E9mIxpo9Gl2rpZMUG3rDozN7Rynw1kuE" --folder -O photos/

      # 4. commit + push any changes back to GitHub
      - name: Commit & push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "🔄 Import photos from Google Drive"
          add: "photos/**"
